# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  ImageName: 'ditiacr001.azurecr.io/aries-cloudagent:$(version)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'ditiacr001'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 
        addBaseImageData: false
    - task: Bash@3
      displayName: 'Tag Docker image'
      inputs:
       targetType: 'inline'
       script: docker tag ditiacr001.azurecr.io/ditiacr001:latest ditiacr001.azurecr.io/aries-cloudagent:py36-1.16-1_0.7.3
    - task: Docker@2
      displayName: 'Push the Docker Image to ACR'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'aries-cloudagent'
        command: 'push'
        tags: ''